apiVersion: batch/v1
kind: CronJob
metadata:
  name: ecr-updater
spec:
  schedule: "0 0 */4 * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ecr-token-updater
            image: quay.io/opsmx-public/ecr-token-updater:latest
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh /opt/updater.sh
          restartPolicy: OnFailure
