apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ecr-updater
spec:
  schedule: "0 */3 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: ecr-token-updater
            env:
            - name: REGION
              valueFrom:
                configMapKeyRef:
                  key: region
                  name: ecr-config
            - name: ACCOUNT
              valueFrom:
                configMapKeyRef:
                  key: account
                  name: ecr-config
            image: quay.io/opsmxpublic/ecr-token-updater:latest
            imagePullPolicy: IfNotPresent
            volumeMounts:
            - name: aws-credentials
              mountPath: /root/.aws
              readOnly: true
          restartPolicy: OnFailure
          volumes:
          - name: aws-credentials
            secret:
              secretName: aws-credentials

